language: node_js
sudo: false
node_js:
  - '7'
  - '6'
  - '4'
cache:
    directories:
      - $HOME/.npm
before_install:
  - npm config set registry https://:2022-02-15T20%3A33%3A33.732000Z@time-machines-npm.sealsecurity.io/
